__author__ = "Huiyun Wu"
__copyright__ = "Copyright 2023, Wu"
__email__ = "hwu18@tulane.edu"
__license__ = "MIT"


import os
import json
import glob
import pandas as pd
from snakemake.utils import validate
shell.executable("bash")


### setup report ####
configfile: "config/config.yaml"

report: "report/workflow.rst"

##### load rules #####


include: "rules/common.smk"
include: "rules/fastp.smk"



### target rules ####



rule all:
    input:
        get_final_output(),
        